feat:finished setup mostly with some optimizations

diff --git a/bin/devfx b/bin/devfx
--- a/bin/devfx
+++ b/bin/devfx
@@ -61,15 +61,17 @@
 
 
  # Use smart_source to load libraries
-  fx_smart_source paths   || exit 1
-  fx_smart_source linker  || exit 1
-  fx_smart_source rcfile  || exit 1
-  fx_smart_source textman || exit 1
-  fx_smart_source package || exit 1
+  fx_smart_source paths    || exit 1
+  fx_smart_source linker   || exit 1
+  fx_smart_source rcfile   || exit 1
+  fx_smart_source template || exit 1
+  fx_smart_source package  || exit 1
 
 #-------------------------------------------------------------------------------
 # 
 #-------------------------------------------------------------------------------
+
+# @lbl options
 
   options(){
     local this next opts=("${@}");
@@ -168,17 +170,22 @@
   }
 
 
+  function_exists(){
+    [ -n "$1" ] && declare -F "$1" >/dev/null
+  }
+
 #-------------------------------------------------------------------------------
 # INIT
 #-------------------------------------------------------------------------------
 
+# @lbl setup
 
   setup(){
-    local res ret;
+    local rc res ret=1;
     init_fx;
     if ensure_fx_setup; then
       okay "System has valid paths.";
-      rc=${!THIS_RC_VAR}; ret=$?;
+      rc=$(fx_get_rc_file);
       if save_rc_file $SELF_PATH $rc "rc:bashfx"; then
         set_profile_link $rc;
       fi
@@ -292,12 +299,56 @@
   }
 
   dev_cleanup(){
-    local rcfile=$(get_rc_file);
+    local rcfile=$(fx_get_rc_file);
 
     printf "found rc %s\n" "$rcfile";
 
   }
 
+# @lbl fx api
+
+#-------------------------------------------------------------------------------
+# FX API
+#-------------------------------------------------------------------------------
+
+  fx_get_rc_file(){
+    local rc ret=1;
+    this_context_fx;
+    rc=${!THIS_RC_VAR}; 
+    [ -n "$rc" ] && { echo $rc; ret=0; }
+    return $ret;
+  }
+
+
+  fx_has_link(){
+    local rc ret=1;
+    rc=$(fx_get_rc_file);
+    has_profile_link && { okay "FX rc file found."; ret=0; }
+    warn "FX link not found ($rc) ($ret)";
+    return $ret;
+  }
+
+
+  fx_del_link(){
+    local rc ret=1;
+    rc=$(fx_get_rc_file);
+    rem_profile_bak "$rc";ret=$?;
+    [ $ret -eq 0 ] && info "FX link removed" || warn "FX already unlinked";
+    return $ret;
+  }
+
+
+  fx_set_link(){
+    local rc ret=1;
+    rc=$(fx_get_rc_file);
+    set_profile_link "$rc"; ret=$?;
+    [ $ret -eq 0 ] && info "FX link added to profile" || warn "Fx could not link to profile";
+    return $ret;
+  }
+
+  fx_print_embed(){
+    dev_print_embed "rc:bashfx"; # @todo print profile block
+  }
 
 #-------------------------------------------------------------------------------
 # System Funcs
@@ -314,15 +365,19 @@
     __boltbox "$str";
   }
 
+# @lbl dispatch
 
   dispatch(){
     local call="$1" arg="$2" exc cmd= ret;
     case $call in
-      (dem*)        cmd='dev_read_embed';;
-      (dlink|devl)  cmd='dev_show_link';;
+      (prof)        cmd='dev_dump_profile';;
+      (docs)        cmd='fx_print_embed';;
+      (has_link)    cmd='fx_has_link';;
+      (link)        cmd='fx_set_link';;
+      (unlink)      cmd='fx_del_link';;
+
       (rc*)         cmd='do_rcfile';;
-      (link)        cmd='do_link';;
-      (unl*)        cmd='do_unlink';;
+
       (init)        cmd='do_init';;
       (inst*)       cmd='do_install_pkg';;
       (pkg)         cmd='do_check_pkg';;
@@ -340,15 +395,20 @@
         fi
       ;;
     esac
-    if [ -n "$cmd" ]; then
+
+    if [ -n "$cmd" ] && function_exists "$cmd"; then
       "$cmd" "$arg" $@;   # Pass all extra arguments if cmd is defined
       ret=$?;
     else
-      echo -ne "\n\n\t"
-      usage    
+      
+       
+      __errbox "Dispatch error, could not find function ($cmd) for command ($call)";
+    
+      
     fi
     [ -n "$err" ] && fatal "$err";
-    echo -ne "\n\n"
+    echo -ne "\n\n";
+
     return $ret;
   }
 
@@ -458,7 +518,7 @@
 #
 # 
 #=================================!doc:help=====================================
-
+# @lbl fx docs
 #=================================rc:bashfx!=====================================
 # ${shebang}
 # 
